In [13]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/IR Proj/scraped_CSV.csv')

In [10]:
import os
print(os.path)
files = [f for f in os.listdir('.') if os.path.isfile(f)]
for f in files:
  print(f)

<module 'posixpath' from '/usr/lib/python3.7/posixpath.py'>

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [16]:
df['title'][139]

'The Hobbit : or There and Back Again'

In [87]:
eval = [2466, 1257, 5774, 646, 8050, 849, 394, 4174, 203, 139, 4097, 61, 173, 1026, 1422, 1148, 1354, 5082, 343, 184, 366, 1108, 4556, 3438, 363, 604, 1313, 140, 264, 221]
len(eval)

30

In [85]:
df.loc[df['title'].str.contains('Web')]

,Unnamed: 0,book_id,review_sentences,title
221,271,6534,"['read', 'still', 'college', 'know', 'never', ...",Charlotte's Web
1575,1981,96594,"['set', 'seems', 'like', 'possible', 'recipe',...",The Devil's Web (Web #3)
3160,4309,1675216,"['initial', 'volume', 'proposed', 'seven', 'bo...",Nora Webster
3217,4398,2072153,"['star', 'one', 'great', 'last', 'one', 'thoug...",A Tangled Web
5443,8082,9680114,"['book', 'damn', 'good', 'mulled', 'felt', 'bo...",Web of Lies
6737,10369,12951824,"['perfect', 'hope', 'final', 'book', 'boonsbor...",Widow's Web
10578,17899,20926961,"['fabulous', 'star', 'earc', 'honest', 'review...",The Gilded Web (Web #1)
13421,24969,33161035,"['finally', 'happy', 'korra', 'graphic', 'nove...","WebMage (Webmage, #1)"
13465,25104,33825562,"['got', 'book', 'netgalley', 'exchange', 'hone...","Black Widow, Volume 2: The Tightly Tangled Web"

In [ ]:
df.loc[df['title'].str.contains('Harry Potter')]

,Unnamed: 0,book_id,review_sentences,title
255,313,7389,"['giving', 'graphic', 'novel', 'figuring', 'st...",Harry Potter and the Philosopher's Stone
575,703,16729,"['loved', 'whole', 'book', 'particularly', 'af...",Harry Potter and the Half-Blood Prince
718,889,24248,"['loved', 'book', 'loved', 'bastien', 'chloe',...",Harry Potter and the Deathly Hallows
807,995,29394,"['painful', 'reading', 'experience', 'academ',...",Harry Potter and the Chamber of Secrets
1016,1236,40223,"['kushiel', 'avatar', 'take', 'place', 'ten', ...",Harry Potter and the Prisoner of Azkaban
2080,2636,218467,"['really', 'enjoyed', 'novel', 'surprise', 'te...",Harry Potter and the Goblet of Fire
2466,3162,363394,"['brought', 'moonlight', 'library', 'battle', ...",Harry Potter and the Order of the Phoenix
3497,4804,3375373,"['seem', 'problem', 'house', 'time', 'get', 'r...","Harry Potter and the Cursed Child, Parts One a..."
6018,9074,11202715,"['one', 'good', 'awesome', 'still', 'hate', 'a...",Harry Potter and the Methods of Rationality

In [ ]:
df.loc[df['title'].str.contains('Rings')]

,Unnamed: 0,book_id,review_sentences,title
1257,1545,60930,"['professional', 'mpreg', 'could', 'think', 'r...",The Lord of the Rings

In [ ]:
df.loc[df['title'].str.contains('Percy Jackson')]

,Unnamed: 0,book_id,review_sentences,title
5774,8644,10596724,"['actual', 'rating', 'book', 'though', 'enough...",Percy Jackson and the Sword of Hades
8491,13621,16650266,"['interactive', 'book', 'fun', 'read', 'three'...",Percy Jackson's Greek Heroes

In [ ]:
df.loc[df['title'].str.contains('Titan\'s')]

,Unnamed: 0,book_id,review_sentences,title
646,799,20249,"['writing', 'one', 'read', 'long', 'ago', 'rev...",The Titan's Curse

In [ ]:
df.loc[df['title'].str.contains('of the Labyrinth')]

,Unnamed: 0,book_id,review_sentences,title
8050,12782,15998792,"['really', 'sweet', 'romance', 'fabulous', 'ch...",The Battle of the Labyrinth

In [ ]:
df.loc[df['title']=='Little Women']

,Unnamed: 0,book_id,review_sentences,title
849,1045,30672,"['time', 'completely', 'engrossing', 'time', '...",Little Women

In [ ]:
df.loc[df['title'].str.contains('Jane Eyre')]

,Unnamed: 0,book_id,review_sentences,title
394,490,12007,"['important', 'start', 'book', 'know', 'main',...",Jane Eyre

In [ ]:
df.loc[df['title'].str.contains('The Notebook')]

,Unnamed: 0,book_id,review_sentences,title
4174,5910,6611038,"['felt', 'story', 'dragged', 'keep', 'forcing'...",The Notebook

In [ ]:
df.loc[df['title']=='Pride and Prejudice']

,Unnamed: 0,book_id,review_sentences,title
203,251,6149,"['novel', 'holy', 'shit', 'moment', 'rends', '...",Pride and Prejudice

In [ ]:
df.loc[df['title'].str.contains('Hobbit')]

,Unnamed: 0,book_id,review_sentences,title
139,172,4630,"['never', 'read', 'hemingway', 'book', 'like',...",The Hobbit : or There and Back Again

In [54]:
def jaccard_similarity(list1, list2):
    #print("doc1", doc1[0], "doc2", doc2[0])
   # union = len(set(doc1).union(set(doc2)))
    #intersection = len(set(doc1).intersection(set(doc2)))
    #print("union ", union)
    #print("intersection ", intersection)

    intersection = len(list(set(list1).intersection(list2)))
    union = (len(list1) + len(list2)) - intersection
    return float(intersection)/union

In [90]:
def ranked_jaccard_similarity(index):
    ranks = []
    reviews = df['review_sentences'][index]
    #print(reviews)
    for i,row in df.iterrows():
        if i == index:
            continue
        else:
            rev = row['review_sentences']
     #       print(rev)
            js = jaccard_similarity(reviews, rev)
            # if(js > 0.0001):
            #   # print("jaccard", js)
            ranks.append((row.title, js))

    return sorted(ranks, key=lambda x: x[1], reverse = True)

In [ ]:
print(ranked_jaccard_similarity(139)[0:10])

In [88]:
eval

[2466,
 1257,
 5774,
 646,
 8050,
 849,
 394,
 4174,
 203,
 139,
 4097,
 61,
 173,
 1026,
 1422,
 1148,
 1354,
 5082,
 343,
 184,
 366,
 1108,
 4556,
 3438,
 363,
 604,
 1313,
 140,
 264,
 221]

In [91]:
eval_rankings = {}

for book in eval:
  eval_rankings[df["title"][book]] = ranked_jaccard_similarity(book)[0:10]

In [92]:
ranked_jaccard_similarity(1)[0:10]

[('Buffy the Vampire Slayer: New Rules', 8.068147215057765e-05),
 ('The Warning', 8.065334412180215e-05),
 ('Uncommon Passion', 8.058499507391724e-05),
 ('Lord of the Flies', 8.056091184557253e-05),
 ('The Painted Girls', 8.055505028194268e-05),
 ('The Racketeer', 8.053161255461862e-05),
 ('One Crazy Summer', 8.05228269226773e-05),
 ("Shakespeare's Christmas (Lily Bard Mysteries Book 3)",
  8.049543642807992e-05),
 ('The Bone Bed', 8.048833049027778e-05),
 ('The Brothers K', 8.048812151109957e-05)]

In [94]:
import json

with open("/content/drive/MyDrive/IR Proj/jaccard_eval.json", 'w') as f: 
    json.dump(eval_rankings, f)

In [95]:
eval_rankings

{'Animal Farm: A Fairy Story': [('Buffy the Vampire Slayer: New Rules',
   0.0001585231776226637),
  ('The Warning', 0.00015841462729126318),
  ('Uncommon Passion', 0.00015815116190087493),
  ('Lord of the Flies', 0.00015805843063274359),
  ('The Painted Girls', 0.0001580358690443418),
  ('The Racketeer', 0.00015794568706373874),
  ('One Crazy Summer', 0.00015791189535025878),
  ("Shakespeare's Christmas (Lily Bard Mysteries Book 3)",
   0.00015780659020682845),
  ('The Bone Bed', 0.00015777928205337012),
  ('The Brothers K', 0.0001577784790154623)],
 'Brave New World': [('Buffy the Vampire Slayer: New Rules',
   0.002278239141618285),
  ('The Warning', 0.0022560221235717924),
  ('Uncommon Passion', 0.0022037392478851214),
  ('Lord of the Flies', 0.0021858694119306164),
  ('The Painted Girls', 0.0021815622800844476),
  ('Waiting on You', 0.0021734405564007822),
  ('Provocative in Pearls', 0.002171867081734598),
  ('Tigerman', 0.0021675760520218253),
  ('The Racketeer', 0.0021645021645021645),
  ('The Memory Key', 0.002158273381294964)],
 'Catch-22': [('Buffy the Vampire Slayer: New Rules', 0.00018430878261076363),
  ('The Warning', 0.00018416206261510129),
  ('Uncommon Passion', 0.00018380609050374727),
  ('Lord of the Flies', 0.00018368084564291258),
  ('The Painted Girls', 0.00018365037707569358),
  ('The Racketeer', 0.00018352860382094712),
  ('One Crazy Summer', 0.0001834829804738596),
  ("Shakespeare's Christmas (Lily Bard Mysteries Book 3)",
   0.00018334082467885785),
  ('The Bone Bed', 0.00018330396527868115),
  ('The Brothers K', 0.00018330288140303572)],
 "Charlotte's Web": [('Buffy the Vampire Slayer: New Rules',
   0.0010607719682452779),
  ('The Warning', 0.0010559302404795968),
  ('Uncommon Passion', 0.0010443336477563671),
  ('Lord of the Flies', 0.0010403033658847613),
  ('The Painted Girls', 0.0010393267844570355),
  ('The Racketeer', 0.0010354387254083303),
  ('One Crazy Summer', 0.0010339881925219305),
  ("Shakespeare's Christmas (Lily Bard Mysteries Book 3)",
   0.0010294899043570668),
  ('The Bone Bed', 0.001028328799840775),
  ('The Brothers K', 0.0010282946893554914)],
 'Divergent': [('Buffy the Vampire Slayer: New Rules', 0.0023613650213284583),
  ('The Warning', 0.0023375056552556177),
  ('Uncommon Passion', 0.002281424786576391),
  ('Lord of the Flies', 0.0022622783332117056),
  ('The Painted Girls', 0.002257665137280606),
  ('Waiting on You', 0.002251576103272291),
  ('Provocative in Pearls', 0.0022498875056247186),
  ('Tigerman', 0.002248062015503876),
  ('The Racketeer', 0.0022393989742107924),
  ('The Memory Key', 0.00223530288354072)],
 'Dune': [('Buffy the Vampire Slayer: New Rules', 0.00010134627078415859),
  ('The Warning', 0.00010130189271149221),
  ('Uncommon Passion', 0.00010119409026512852),
  ('Lord of the Flies', 0.00010115611651879383),
  ('The Painted Girls', 0.00010114687505098128),
  ('The Racketeer', 0.00010110992605928955),
  ('One Crazy Summer', 0.00010109607714609035),
  ("Shakespeare's Christmas (Lily Bard Mysteries Book 3)",
   0.00010105290608599277),
  ('The Bone Bed', 0.00010104170740929062),
  ('The Brothers K', 0.00010104137807402095)],
 'Fahrenheit 451': [('Buffy the Vampire Slayer: New Rules',
   0.0007992574640334141),
  ('The Warning', 0.0007965056526207606),
  ('Uncommon Passion', 0.0007898894154818325),
  ('Lord of the Flies', 0.0007875816163207236),
  ('The Painted Girls', 0.0007870217573434208),
  ('The Racketeer', 0.000784790258474469),
  ('One Crazy Summer', 0.0007839567053587234),
  ("Shakespeare's Christmas (Lily Bard Mysteries Book 3)",
   0.0007813681504259717),
  ('The Bone Bed', 0.0007806991034552232),
  ('The Brothers K', 0.0007806794429474427)],
 'Harry Potter and the Order of the Phoenix': [('Buffy the Vampire Slayer: New Rules',
   0.0027185828290800665),
  ('The Warning', 0.002687007020889313),
  ('Uncommon Passion', 0.0026131669898002193),
  ('Tigerman', 0.0025950782997762865),
  ('Lord of the Flies', 0.002588078143262648),
  ('Waiting on You', 0.002586429864643504),
  ('Provocative in Pearls', 0.002584201912309415),
  ('The Painted Girls', 0.0025820423121772447),
  ('The Memory Key', 0.0025649794801641587),
  ('The Racketeer', 0.002558177917148044)],
 'Jane Eyre': [('Buffy the Vampire Slayer: New Rules', 0.0003537883888933271),
  ('The Warning', 0.0003532481739348428),
  ('Uncommon Passion', 0.0003519407831250071),
  ('Lord of the Flies', 0.000351481893013447),
  ('The Painted Girls', 0.00035137034434293746),
  ('The Racketeer', 0.0003509248568000181),
  ('One Crazy Summer', 0.0003507580900656257),
  ("Shakespeare's Christmas (Lily Bard Mysteries Book 3)",
   0.00035023895335043105),
  ('The Bone Bed', 0.000350104466655373),
  ('The Brothers K', 0.00035010051272784765)],
 'Little Women': [('Buffy the Vampire Slayer: New Rules',
   0.001998968274438999),
  ('The Warning', 0.001981843753995653),
  ('Uncommon Passion', 0.0019413827655310621),
  ('Lord of the Flies', 0.001927501088105453),
  ('The Painted Girls', 0.0019241512010427658),
  ('The Racketeer', 0.001910867287184861),
  ('Waiting on You', 0.0019103413143148242),
  ('Provocative in Pearls', 0.0019091256204658267),
  ('One Crazy Summer', 0.0019059329849369813),
  ('The Memory Key', 0.0018986140117714068)],
 'Lord of the Flies': [('Buffy the Vampire Slayer: New Rules',
   0.008284339925173703),
  ('Tigerman', 0.008252703471826979),
  ('Cologne', 0.008211143695014663),
  ('The Warning', 0.007997936016511867),
  ('A Hidden Fire', 0.007760532150776054),
  ('Waiting on You', 0.007618080243778568),
  ('Provocative in Pearls', 0.007598784194528876),
  ('The Memory Key', 0.007434944237918215),
  ('Uncommon Passion', 0.007377439314612089),
  ('The Radleys', 0.007267441860465116)],
 'Percy Jackson and the Sword of Hades': [('Buffy the Vampire Slayer: New Rules',
   0.00030478512648582747),
  ('The Warning', 0.000304384113113064),
  ('Uncommon Passion', 0.00030341290581476155),
  ('Lord of the Flies', 0.0003030717791291086),
  ('The Painted Girls', 0.000302988838282151),
  ('The Racketeer', 0.00030265752836193934),
  ('One Crazy Summer', 0.00030253347386501153),
  ("Shakespeare's Christmas (Lily Bard Mysteries Book 3)",
   0.00030214719441709956),
  ('The Bone Bed', 0.0003020470998606686),
  ('The Brothers K', 0.0003020441569070678)],
 'Pride and Prejudice': [('Buffy the Vampire Slayer: New Rules',
   0.0002325563949257695),
  ('The Warning', 0.00023232285382395924),
  ('Uncommon Passion', 0.00023175664057535454),
  ('Lord of the Flies', 0.0002315575607278377),
  ('The Painted Girls', 0.00023150914087704624),
  ('The Racketeer', 0.00023131566380133714),
  ('One Crazy Summer', 0.00023124319324471497),
  ("Shakespeare's Christmas (Lily Bard Mysteries Book 3)",
   0.00023101744554322634),
  ('The Bone Bed', 0.00023095892656251163),
  ('The Brothers K', 0.00023095720586482297)],
 'The Adventures of Tom Sawyer': [('Buffy the Vampire Slayer: New Rules',
   0.0004793122642092894),
  ('The Warning', 0.000478321246721185),
  ('Uncommon Passion', 0.00047592729059199216),
  ('Lord of the Flies', 0.0004750885043907373),
  ('The Painted Girls', 0.00047488472556258524),
  ('The Racketeer', 0.0004740713553852977),
  ('One Crazy Summer', 0.00047376705943484175),
  ("Shakespeare's Christmas (Lily Bard Mysteries Book 3)",
   0.00047282045024708684),
  ('The Bone Bed', 0.00047257538339583524),
  ('The Brothers K', 0.00047256817939297853)],
 'The Battle of the Labyrinth': [('Buffy the Vampire Slayer: New Rules',
   0.0015764849471114728),
  ('The Warning', 0.0015658147287604808),
  ('Uncommon Passion', 0.0015404492148678194),
  ('Lord of the Flies', 0.0015316962300508919),
  ('The Painted Girls', 0.0015295801055903685),
  ('The Racketeer', 0.0015211737572991806),
  ('One Crazy Summer', 0.001518045149600901),
  ('Waiting on You', 0.0015105740181268882),
  ('Provocative in Pearls', 0.001509813789632612),
  ("Shakespeare's Christmas (Lily Bard Mysteries Book 3)",
   0.0015083690151810043)],
 'The Book Thief': [('Buffy the Vampire Slayer: New Rules',
   0.0015402961343535726),
  ('The Warning', 0.0015301085883514315),
  ('Uncommon Passion', 0.0015058777810162247),
  ('Lord of the Flies', 0.0014975121974783827),
  ('The Painted Girls', 0.0014954894109701384),
  ('The Racketeer', 0.0014874526174367833),
  ('One Crazy Summer', 0.0014844610448690322),
  ('Waiting on You', 0.0014762326542663124),
  ('Provocative in Pearls', 0.0014755065905961047),
  ("Shakespeare's Christmas (Lily Bard Mysteries Book 3)",
   0.0014752070048539069)],
 'The Fault in Our Stars': [('Buffy the Vampire Slayer: New Rules',
   0.000912999941096778),
  ('The Warning', 0.0009094109363999061),
  ('Uncommon Passion', 0.0009007961875980706),
  ('Lord of the Flies', 0.0008977960554895885),
  ('The Painted Girls', 0.0008970686112799144),
  ('The Racketeer', 0.0008941705846721856),
  ('One Crazy Summer', 0.0008930886462504682),
  ("Shakespeare's Christmas (Lily Bard Mysteries Book 3)",
   0.0008897307846851501),
  ('The Bone Bed', 0.0008888634017662576),
  ('The Brothers K', 0.0008888379161051695)],
 'The Giver': [('Buffy the Vampire Slayer: New Rules', 0.003297872340425532),
  ('The Warning', 0.003251520872666247),
  ('Tigerman', 0.0031617967727867423),
  ('Uncommon Passion', 0.0031440162271805273),
  ('Waiting on You', 0.003126302626094206),
  ('Provocative in Pearls', 0.003123048094940662),
  ('Lord of the Flies', 0.0031077694235588974),
  ('The Painted Girls', 0.003099070278916325),
  ('The Memory Key', 0.0030950170225936243),
  ('Cologne', 0.0030877812086457872)],
 'The Great Gatsby': [('Buffy the Vampire Slayer: New Rules',
   0.0017475618693274706),
  ('The Warning', 0.0017344597996978683),
  ('Uncommon Passion', 0.0017033902961701192),
  ('Lord of the Flies', 0.0016926941137927268),
  ('The Painted Girls', 0.0016901101297568423),
  ('The Racketeer', 0.0016798526064809797),
  ('One Crazy Summer', 0.0016760380622837371),
  ('Waiting on You', 0.0016727069974909396),
  ('Provocative in Pearls', 0.0016717748676511562),
  ("Shakespeare's Christmas (Lily Bard Mysteries Book 3)",
   0.0016642508187040318)],
 'The Hobbit : or There and Back Again': [('Buffy the Vampire Slayer: New Rules',
   0.005198725473754821),
  ('The Warning', 0.005084467771034935),
  ('Tigerman', 0.005056669572798605),
  ('Cologne', 0.004972473805718345),
  ('Waiting on You', 0.004870920603994155),
  ('Provocative in Pearls', 0.004863024801426487),
  ('Uncommon Passion', 0.004826405106647984),
  ('A Hidden Fire', 0.004803568365071196),
  ('The Memory Key', 0.00479539641943734),
  ('Lord of the Flies', 0.004741511165494035)],
 'The Hunger Games': [('Buffy the Vampire Slayer: New Rules',
   0.0012051002954439434),
  ('The Warning', 0.0011988552865650863),
  ('Uncommon Passion', 0.0011839291170180264),
  ('Lord of the Flies', 0.001178752043803947),
  ('The Painted Girls', 0.001177498385687697),
  ('The Racketeer', 0.0011725103067438253),
  ('One Crazy Summer', 0.0011706506551867376),
  ("Shakespeare's Christmas (Lily Bard Mysteries Book 3)",
   0.001164888020441906),
  ('The Bone Bed', 0.0011634016362681078),
  ('The Brothers K', 0.0011633579765076745)],
 'The Kite Runner': [('Buffy the Vampire Slayer: New Rules',
   5.639962958178765e-05),
  ('The Warning', 5.63858831575367e-05),
  ('Uncommon Passion', 5.6352468329003886e-05),
  ('Lord of the Flies', 5.634069033702637e-05),
  ('The Painted Girls', 5.6337823397279795e-05),
  ('The Racketeer', 5.632635855542877e-05),
  ('One Crazy Summer', 5.632206044265506e-05),
  ("Shakespeare's Christmas (Lily Bard Mysteries Book 3)",
   5.630865863693085e-05),
  ('The Bone Bed', 5.6305181348091346e-05),
  ('The Brothers K', 5.6305079081391714e-05)],
 'The Lion, the Witch and the Wardrobe': [('Buffy the Vampire Slayer: New Rules',
   0.0012798282553050946),
  ('The Warning', 0.001272786992938085),
  ('Uncommon Passion', 0.0012559760149096508),
  ('Lord of the Flies', 0.0012501512279711256),
  ('The Painted Girls', 0.0012487411883182276),
  ('The Racketeer', 0.0012431326943898625),
  ('One Crazy Summer', 0.0012410424756795707),
  ("Shakespeare's Christmas (Lily Bard Mysteries Book 3)",
   0.0012345679012345679),
  ('The Bone Bed', 0.0012328985046134266),
  ('The Brothers K', 0.0012328494730562737)],
 'The Lord of the Rings': [('Buffy the Vampire Slayer: New Rules',
   0.0013291030697993483),
  ('The Warning', 0.0013215107852331826),
  ('Uncommon Passion', 0.001303397241843256),
  ('Lord of the Flies', 0.0012971254027365161),
  ('The Painted Girls', 0.0012956074727295524),
  ('The Racketeer', 0.0012895711136070552),
  ('One Crazy Summer', 0.001287321955068311),
  ("Shakespeare's Christmas (Lily Bard Mysteries Book 3)",
   0.0012803568478440442),
  ('The Bone Bed', 0.0012785614121917017),
  ('The Brothers K', 0.0012785086814863695)],
 'The Notebook': [('Buffy the Vampire Slayer: New Rules',
   0.00018624770945357326),
  ('The Warning', 0.00018609788748881912),
  ('Uncommon Passion', 0.00018573439980827417),
  ('Lord of the Flies', 0.00018560651418991737),
  ('The Painted Girls', 0.00018557540347684498),
  ('The Racketeer', 0.00018545106484804978),
  ('One Crazy Summer', 0.00018540448080764583),
  ("Shakespeare's Christmas (Lily Bard Mysteries Book 3)",
   0.00018525933318592268),
  ('The Bone Bed', 0.0001852216984232256),
  ('The Brothers K', 0.00018522059174991634)],
 'The Subtle Art of Not Giving a F*ck: A Counterintuitive Approach to Living a Good Life': [('Buffy the Vampire Slayer: New Rules',
   0.0018832391713747645),
  ('The Warning', 0.001868032539921663),
  ('Uncommon Passion', 0.0018320430234619704),
  ('Lord of the Flies', 0.0018196759802770602),
  ('The Painted Girls', 0.0018166901078293482),
  ('The Racketeer', 0.0018048439683278994),
  ('Waiting on You', 0.0018010446058714055),
  ('One Crazy Summer', 0.0018004413985364153),
  ('Provocative in Pearls', 0.0017999640007199855),
  ('The Memory Key', 0.0017906171660498984)],
 "The Titan's Curse": [('Buffy the Vampire Slayer: New Rules',
   0.002570907281472881),
  ('The Warning', 0.0025426509186351706),
  ('Uncommon Passion', 0.002476433935133408),
  ('Lord of the Flies', 0.00245389060397372),
  ('Tigerman', 0.0024513947590870666),
  ('The Painted Girls', 0.0024484637864307717),
  ('Waiting on You', 0.002448180186061694),
  ('Provocative in Pearls', 0.002446183953033268),
  ('The Memory Key', 0.002428953121204761),
  ('The Racketeer', 0.0024269944413998277)],
 'The Wolf of Wall Street': [('Buffy the Vampire Slayer: New Rules',
   5.112567184905063e-05),
  ('The Warning', 5.111437583576127e-05),
  ('Uncommon Passion', 5.108691532261387e-05),
  ('Lord of the Flies', 5.1077235370491197e-05),
  ('The Painted Girls', 5.107487906786698e-05),
  ('The Racketeer', 5.1065456030995084e-05),
  ('One Crazy Summer', 5.106192328851963e-05),
  ("Shakespeare's Christmas (Lily Bard Mysteries Book 3)",
   5.105090763573366e-05),
  ('The Bone Bed', 5.1048049388164426e-05),
  ('The Brothers K', 5.104796532690458e-05)],
 'To Kill a Mockingbird': [('Buffy the Vampire Slayer: New Rules',
   0.0007531767049733959),
  ('The Warning', 0.0007507325696849345),
  ('Uncommon Passion', 0.0007448521108147721),
  ('Lord of the Flies', 0.0007427996357885657),
  ('The Painted Girls', 0.0007423016139073799),
  ('The Racketeer', 0.0007403161866552037),
  ('One Crazy Summer', 0.0007395743868689761),
  ("Shakespeare's Christmas (Lily Bard Mysteries Book 3)",
   0.0007372701976359788),
  ('The Bone Bed', 0.0007366745086856301),
  ('The Brothers K', 0.0007366570029941542)],
 'Wuthering Heights': [('Buffy the Vampire Slayer: New Rules',
   0.00022665789281275134),
  ('The Warning', 0.00022643604277449892),
  ('Uncommon Passion', 0.00022589812723165488),
  ('Lord of the Flies', 0.00022570898103316464),
  ('The Painted Girls', 0.0002256629759850917),
  ('The Racketeer', 0.00022547914317925591),
  ('One Crazy Summer', 0.00022541028307168775),
  ("Shakespeare's Christmas (Lily Bard Mysteries Book 3)",
   0.0002251957750366851),
  ('The Bone Bed', 0.00022514016791098975),
  ('The Brothers K', 0.00022513853282301932)]}